// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

//指定包名

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sex int32

const (
	Sex_Man   Sex = 0
	Sex_Women Sex = 1
)

var Sex_name = map[int32]string{
	0: "Man",
	1: "Women",
}

var Sex_value = map[string]int32{
	"Man":   0,
	"Women": 1,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}

func (Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

//标示位被系统占用的是 19000  19999
type Stu struct {
	Score int32  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	//放切片
	ClassName []string `protobuf:"bytes,4,rep,name=ClassName,proto3" json:"ClassName,omitempty"`
	//message嵌套
	T *Teacher `protobuf:"bytes,5,opt,name=t,proto3" json:"t,omitempty"`
	//枚举
	S Sex `protobuf:"varint,6,opt,name=s,proto3,enum=pb.Sex" json:"s,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Stu_ParentName
	//	*Stu_Age
	Data                 isStu_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Stu) Reset()         { *m = Stu{} }
func (m *Stu) String() string { return proto.CompactTextString(m) }
func (*Stu) ProtoMessage()    {}
func (*Stu) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Stu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stu.Unmarshal(m, b)
}
func (m *Stu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stu.Marshal(b, m, deterministic)
}
func (m *Stu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stu.Merge(m, src)
}
func (m *Stu) XXX_Size() int {
	return xxx_messageInfo_Stu.Size(m)
}
func (m *Stu) XXX_DiscardUnknown() {
	xxx_messageInfo_Stu.DiscardUnknown(m)
}

var xxx_messageInfo_Stu proto.InternalMessageInfo

func (m *Stu) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Stu) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stu) GetClassName() []string {
	if m != nil {
		return m.ClassName
	}
	return nil
}

func (m *Stu) GetT() *Teacher {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *Stu) GetS() Sex {
	if m != nil {
		return m.S
	}
	return Sex_Man
}

type isStu_Data interface {
	isStu_Data()
}

type Stu_ParentName struct {
	ParentName string `protobuf:"bytes,7,opt,name=parentName,proto3,oneof"`
}

type Stu_Age struct {
	Age int32 `protobuf:"varint,8,opt,name=age,proto3,oneof"`
}

func (*Stu_ParentName) isStu_Data() {}

func (*Stu_Age) isStu_Data() {}

func (m *Stu) GetData() isStu_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Stu) GetParentName() string {
	if x, ok := m.GetData().(*Stu_ParentName); ok {
		return x.ParentName
	}
	return ""
}

func (m *Stu) GetAge() int32 {
	if x, ok := m.GetData().(*Stu_Age); ok {
		return x.Age
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Stu) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Stu_ParentName)(nil),
		(*Stu_Age)(nil),
	}
}

type Teacher struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Teacher) Reset()         { *m = Teacher{} }
func (m *Teacher) String() string { return proto.CompactTextString(m) }
func (*Teacher) ProtoMessage()    {}
func (*Teacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Teacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Teacher.Unmarshal(m, b)
}
func (m *Teacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Teacher.Marshal(b, m, deterministic)
}
func (m *Teacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Teacher.Merge(m, src)
}
func (m *Teacher) XXX_Size() int {
	return xxx_messageInfo_Teacher.Size(m)
}
func (m *Teacher) XXX_DiscardUnknown() {
	xxx_messageInfo_Teacher.DiscardUnknown(m)
}

var xxx_messageInfo_Teacher proto.InternalMessageInfo

func (m *Teacher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Teacher) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Sex", Sex_name, Sex_value)
	proto.RegisterType((*Stu)(nil), "pb.Stu")
	proto.RegisterType((*Teacher)(nil), "pb.Teacher")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x6a, 0xf3, 0x30,
	0x10, 0x84, 0xb3, 0x51, 0x1c, 0xc7, 0x9b, 0x9f, 0x9f, 0xb0, 0xb4, 0xe0, 0x94, 0x1e, 0x44, 0x4e,
	0xa6, 0x07, 0x17, 0xdc, 0x37, 0x68, 0xa0, 0xf8, 0xd2, 0x1e, 0xe4, 0x42, 0xce, 0xb2, 0x23, 0xda,
	0x83, 0x22, 0x19, 0x49, 0x86, 0xbc, 0x5c, 0xdf, 0xad, 0xc8, 0x2e, 0xad, 0x6f, 0xbb, 0x33, 0x48,
	0xf3, 0xcd, 0xe2, 0xbf, 0x5e, 0x39, 0x6f, 0x4d, 0xd9, 0x3b, 0x1b, 0x2c, 0x2d, 0xfb, 0xf6, 0xf0,
	0x05, 0xc8, 0x9a, 0x30, 0xd0, 0x0d, 0x26, 0xbe, 0xb3, 0x4e, 0xe5, 0xc0, 0xa1, 0x48, 0xc4, 0xb4,
	0x10, 0xe1, 0xca, 0xc8, 0x8b, 0xca, 0x19, 0x87, 0x22, 0x13, 0xe3, 0x4c, 0xf7, 0x98, 0x1d, 0xb5,
	0xf4, 0xfe, 0x2d, 0x1a, 0x2b, 0xce, 0x8a, 0x4c, 0xfc, 0x09, 0xb4, 0x47, 0x08, 0x79, 0xc2, 0xa1,
	0xd8, 0x56, 0xdb, 0xb2, 0x6f, 0xcb, 0x77, 0x25, 0xbb, 0x4f, 0xe5, 0x04, 0x04, 0xba, 0x45, 0xf0,
	0xf9, 0x9a, 0x43, 0xf1, 0xbf, 0x4a, 0xa3, 0xd5, 0xa8, 0xab, 0x00, 0x4f, 0x1c, 0xb1, 0x97, 0x4e,
	0x99, 0x30, 0x7e, 0x98, 0xc6, 0xa4, 0x7a, 0x21, 0x66, 0x1a, 0x11, 0x32, 0xf9, 0xa1, 0xf2, 0x4d,
	0x24, 0xab, 0x17, 0x22, 0x2e, 0xcf, 0x6b, 0x5c, 0x9d, 0x65, 0x90, 0x87, 0x47, 0x4c, 0x7f, 0x22,
	0x7e, 0x61, 0x61, 0x06, 0xbb, 0x9b, 0x9e, 0x2e, 0xc7, 0x52, 0x71, 0x7c, 0xd8, 0x23, 0x6b, 0xd4,
	0x95, 0x52, 0x64, 0xaf, 0xd2, 0xec, 0x16, 0x94, 0x61, 0x72, 0xb2, 0x17, 0x65, 0x76, 0x50, 0x95,
	0x88, 0xb5, 0xd2, 0xda, 0x9e, 0xac, 0xd3, 0x67, 0xe2, 0xb8, 0x39, 0x4a, 0xad, 0x5f, 0x06, 0xd3,
	0xd1, 0xc4, 0x1b, 0x86, 0xbb, 0x79, 0xa7, 0x76, 0x3d, 0x9e, 0xf1, 0xe9, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x51, 0x10, 0xfb, 0x73, 0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldClient interface {
	CallFunc(ctx context.Context, in *Stu, opts ...grpc.CallOption) (*Teacher, error)
}

type helloWorldClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldClient(cc *grpc.ClientConn) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) CallFunc(ctx context.Context, in *Stu, opts ...grpc.CallOption) (*Teacher, error) {
	out := new(Teacher)
	err := c.cc.Invoke(ctx, "/pb.HelloWorld/CallFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	CallFunc(context.Context, *Stu) (*Teacher, error)
}

// UnimplementedHelloWorldServer can be embedded to have forward compatible implementations.
type UnimplementedHelloWorldServer struct {
}

func (*UnimplementedHelloWorldServer) CallFunc(ctx context.Context, req *Stu) (*Teacher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallFunc not implemented")
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_CallFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stu)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).CallFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HelloWorld/CallFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).CallFunc(ctx, req.(*Stu))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallFunc",
			Handler:    _HelloWorld_CallFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
